# 错误相关关键词组
[group.errors]
match_case = false
whole_word = false
use_regex = false

error1 = { key = "ERROR", annotation = "错误级别日志" }
error2 = { key = "Exception", annotation = "异常信息" }
error3 = { key = "Failed", annotation = "失败信息" }
error4 = { key = "失败", annotation = "中文失败信息" }
error5 = { key = "错误", annotation = "中文错误信息" }

# 警告相关关键词组
[group.warnings]
match_case = false
whole_word = false
use_regex = false

warning1 = { key = "WARNING", annotation = "警告级别日志" }
warning2 = { key = "WARN", annotation = "警告简写" }
warning3 = { key = "警告", annotation = "中文警告信息" }
warning4 = { key = "注意", annotation = "中文注意信息" }

# 信息相关关键词组
[group.info]
match_case = false
whole_word = false
use_regex = false

info1 = { key = "INFO", annotation = "信息级别日志" }
info2 = { key = "NOTICE", annotation = "通知信息" }
info3 = { key = "信息", annotation = "中文信息" }

# 调试相关关键词
[group.debug]
match_case = false
whole_word = false
use_regex = false

debug1 = { key = "DEBUG", annotation = "调试级别日志" }
debug2 = { key = "TRACE", annotation = "追踪级别日志" }
debug3 = { key = "调试", annotation = "中文调试信息" }

# 正则表达式组
[group.regex]
match_case = false
whole_word = false
use_regex = true

ip = { key = "\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}", annotation = "IP地址" }
timestamp = { key = "\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}", annotation = "时间戳" }
uuid = { key = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", annotation = "UUID" }
memory = { key = "(\\d+)([KMG]B|[kmg]b)", annotation = "内存使用量" }

# 系统相关关键词
[group.system]
match_case = false
whole_word = false
use_regex = false

cpu = { key = "CPU", annotation = "CPU相关" }
memory = { key = "Memory", annotation = "内存相关" }
disk = { key = "Disk", annotation = "磁盘相关" }
network = { key = "Network", annotation = "网络相关" }
timeout = { key = "Timeout", annotation = "超时" }
overload = { key = "Overload", annotation = "过载" }

# 安全相关关键词
[group.security]
match_case = false
whole_word = true
use_regex = false

access = { key = "Access denied", annotation = "访问拒绝" }
auth = { key = "Authentication failed", annotation = "认证失败" }
permission = { key = "Permission", annotation = "权限问题" }
firewall = { key = "Firewall", annotation = "防火墙" }
attack = { key = "Attack", annotation = "攻击" } 